// ValidateNewAccountPassswordMissingCharactersError
using Disney.Mix.SDK;

internal class ValidateNewAccountPassswordMissingCharactersError : IValidateNewAccountPassswordMissingCharactersError, IValidateNewAccountError
{
}
