// IReuseExistingGuestControllerLoginCorruptionDetectedResult
using Disney.Mix.SDK;

public interface IReuseExistingGuestControllerLoginCorruptionDetectedResult : IReuseExistingGuestControllerLoginResult
{
}
